---
- hosts: all
  roles:
    - role: amygos.nethserver_vagrant_base_setup

    - role: amygos.nethserver_install_packages
      packages_lists:
        - pkgs:
            - "@nethserver-backup"
          enablerepo:
            - nethserver-testing
